### ISSUE TITLE
Documentation git action fails

### ISSUE THREAD

**Issue by DenSto** [stellaGK/stella#82]
Recently, the documentation git action has been failing with this error:

`Traceback (most recent call last):
  File "/home/runner/.local/bin/ford", line 5, in <module>
    from ford import run
  File "/home/runner/.local/lib/python3.8/site-packages/ford/__init__.py", line 41, in <module>
    import ford.output
  File "/home/runner/.local/lib/python3.8/site-packages/ford/output.py", line 44, in <module>
    loader=jinja2.FileSystemLoader(loc / "templates"),
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 163, in __init__
    self.searchpath = list(searchpath)
TypeError: 'PosixPath' object is not iterable
Error: Process completed with exit code 1.`

Peter, do you know what this might mean?

**Comment by ZedThree** [comment]
Eep. I'll investigate!
